run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - goimports
    - revive
    - gocritic
    - gocyclo
    - dupl
    - unconvert
    - prealloc
    - misspell
    - bodyclose

linters-settings:
  gocyclo:
    min-complexity: 15
  gocritic:
    enabled-tags: [diagnostic, performance, style]
    disabled-checks: [hugeParam, rangeValCopy]
  revive:
    rules:
      - name: var-naming
      - name: exported
      - name: error-strings
      - name: error-return
      - name: error-naming
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: early-return
      - name: unused-parameter

issues:
  exclude-rules:
    - path: _test\.go$
      linters: [gocyclo, dupl, gocritic, revive]
